from fastapi import FastAPI, HTTPException, Request
import os
import time
import uuid
import logging
import httpx
from pydantic import BaseModel
from typing import Optional, Dict, Any

logging.basicConfig(level=logging.INFO, format='{"time": "%(asctime)s", "level": "%(levelname)s", "message": "%(message)s"}')
logger = logging.getLogger(__name__)

app = FastAPI(title="Inference Service", version="1.0.0")

class InferenceRequest(BaseModel):
    prompt: str
    image_base64: Optional[str] = None
    max_tokens: int = 1000
    temperature: float = 0.2

class InferenceResponse(BaseModel):
    text: str
    metadata: Dict[str, Any]

class GeminiInferenceModel:
    def __init__(self):
        self.model_name = os.getenv("GEMINI_MODEL_NAME", "gemini-2.5-flash")
        self.loaded = True

    async def generate_async(self, prompt: str, image_base64: Optional[str] = None, temperature: float = 0.2) -> str:
        api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable is missing. Please provide a Google AI Studio API key in settings or .env.")

        parts = []
        if image_base64:
            b64_data = image_base64
            mime_type = "image/jpeg"
            if "," in image_base64:
                header, b64_data = image_base64.split(",", 1)
                if "jpeg" in header or "jpg" in header:
                    mime_type = "image/jpeg"
                elif "png" in header:
                    mime_type = "image/png"
                elif "webp" in header:
                    mime_type = "image/webp"

            parts.append({
                "inline_data": {
                    "mime_type": mime_type,
                    "data": b64_data
                }
            })

        parts.append({"text": prompt})

        payload = {
            "contents": [{"parts": parts}],
            "generationConfig": {
                "temperature": temperature,
                "responseMimeType": "application/json"
            }
        }

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={api_key}"
        
        async with httpx.AsyncClient(timeout=60.0) as client:
            headers = {"User-Agent": "aistudio-build"}
            response = await client.post(url, json=payload, headers=headers)
            if response.status_code != 200:
                logger.error(f"Gemini API error ({response.status_code}): {response.text}")
                raise RuntimeError(f"Gemini API Error ({response.status_code}): {response.text}")

            res_data = response.json()
            candidates = res_data.get("candidates", [])
            if not candidates:
                raise RuntimeError("No candidate response generated by Gemini API.")

            content_parts = candidates[0].get("content", {}).get("parts", [])
            text_result = "".join([p.get("text", "") for p in content_parts])
            return text_result

model: Optional[GeminiInferenceModel] = None

@app.on_event("startup")
def startup_event():
    global model
    logger.info("Initializing Gemini Inference Model...")
    model = GeminiInferenceModel()
    logger.info(f"Gemini Inference Model initialized (Target Model: {model.model_name})")

@app.post("/infer", response_model=InferenceResponse)
async def infer(request: InferenceRequest, req: Request):
    request_id = req.headers.get("X-Request-ID", str(uuid.uuid4()))
    logger.info(f"Received inference request {request_id}")
    
    start_time = time.time()
    try:
        if not model or not model.loaded:
            raise HTTPException(status_code=503, detail="Model not initialized")
            
        output = await model.generate_async(request.prompt, request.image_base64, request.temperature)
        
        latency = int((time.time() - start_time) * 1000)
        
        logger.info(f"Inference completed {request_id} in {latency}ms")
        return InferenceResponse(
            text=output,
            metadata={
                "model": model.model_name,
                "latency_ms": latency,
                "request_id": request_id
            }
        )
    except Exception as e:
        logger.error(f"Inference error {request_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
def health_check():
    if model and model.loaded:
        return {"status": "healthy", "model": model.model_name}
    return {"status": "unhealthy", "reason": "Model not loaded"}, 503

@app.get("/ready")
def ready_check():
    return health_check()

@app.get("/status")
def status_check():
    return {"status": "running"}

@app.get("/metrics")
def metrics():
    return {"status": "ok"}
